language: go
go:
  - 1.4.2
  - 1.5
env:
  - GOARCH: amd64
  - GOARCH: 386
script:
  - go test -v
notifications:
  email:
    recipients:
      - brian.downs@gmail.com
    on_success: change
    on_failure: always